### ISSUE TITLE
Seeming contradiction between "each time" and "no restriction on the ratio"

### ISSUE THREAD

**Issue by aaronshaf** [callbag/callbag#10]
> "Pullable: a source that delivers data to a sink for *each time* it is delivered data from the sink"

"Each time" seems to imply a 1:1 ratio. But later:

> However, this spec puts no restriction on the ratio of source deliveries versus sink deliveries in a pull relationship between source and sink.

**Comment by aaronshaf** [comment]
Ah. So it's saying: Not all sink/source relationships are that of pullers/pullables, but when they are, it is 1:1.

**Comment by bloodyKnuckles** [comment]
Does this make sense without confusing people early on?

> Pullable: a source that typically delivers data to a sink each time it is delivered data from the sink

**Comment by aaronshaf** [comment]
It doesn't seem typical:

https://github.com/callbag/callbag/blob/master/getting-started.md#pullable

**Comment by aaronshaf** [comment]
Reopened. I'll let someone else close it.

**Comment by bloodyKnuckles** [comment]
> It doesn't seem typical:

```
function source(start, sink) {
  if (start !== 0) return;
  let i = 10;
  const talkback = (t, d) => {
    if (t === 1) {
      if (i <= 20) sink(1, i++);
      else sink(2);
    }
  };
  sink(0, talkback);
}
```

That reads 1:1 to me. Am I missing something?

**Comment by staltz** [comment]
Pullables are always 1:1 ratio. And Aaron was right to notice that not all sources are strictly listenables xor pullables.

**Comment by staltz** [comment]
I could try to clarify in the spec.

**Comment by staltz** [comment]
I actually ended up removing puller/pullable/listener/listenable terminology from the spec since it was in the definitions but not referred in the protocol. Now the protocol has less opinions, it's more descriptive.
