### ISSUE TITLE
Why flatten's outerSource can not receive the message of last sink?

### ISSUE THREAD

**Issue by janryWang** [callbag/callbag#21]
like this.

https://github.com/staltz/callbag-flatten/blob/master/index.js#L10

InnerSource response priority is higher than outerSource. Why? Is there some special constraint?

Can it be changed like this?

```
if (t === 1) {
      innerTalkback && innerTalkback(1,d);
      outerTalkback && outerTalkback(1,d);
}
```

I tried to change it, but unfortunately the test case could not be passed.

**Comment by staltz** [comment]
The outerSource exists only to present the innerSource to the sink. So when the sink communicates with the source, it needs to communicate with the innerSource (over time, multiple innerSources!), and the outerSource is just a factory of innerSources. While there exists an innerSource, we don't need to create a new innerSource, so we don't need to call the outerTalkback.
