### ISSUE TITLE
Сreate a callbag from a react event

### ISSUE THREAD

**Issue by saitonakamura** [callbag/callbag#22]
The idea behind callbags is great, but it's not easy to seamlessly integrate it with react. The problem is lying in that fact that Listenable factory should have just enough information in factory arguments to subscribe to some event and emit `sink(1, data)` in this case. But with react way of passing a handler function it's not so easy. Let's imagine small react component

```
class MyComponent extends React.Component {
  handleClick() => {}

  render() {
    return <button onClick={this.handleClick} />
  }
}
```

What we want to do is to somehow subscribe to the calls of `handleClick` with callbag factory and use the event, something like this

```
class MyComponent extends React.Component {
  constructor(props) {
    super(props)

    pipe(
      reactEvent(this.handleClick),
      observe(event => this.props.onClick(event))
    )
  }

  handleClick() => {}

  render() {
    return <button onClick={this.handleClick} />
  }
}
```

But a reference to the function is not enough to subscribe to its calls, to do it we need to ask a handler to call some method (which is `sink(1, event)`), but we don't have the `sink` until someone will do a handshake, so it's basically chicken and egg problem.

I puzzled over it and came up with this solution, there will be a ref-like callback to set our handler

```
class MyComponent extends React.Component {
  handleClick

  constructor(props) {
    super(props)

    pipe(
      reactEvent(send => { this.handleClick = send }),
      observe(event => this.props.onClick(event))
    )
  }

  render() {
    return <button onClick={this.handleClick} />
  }
}
```

with the implementation of `reactEvent`

```
const reactEvent = cb => (start, sink) => {
  if (start !== 0) return
  const talkback = (t, d) => {
    if (t === 2) cb(null)
  }
  sink(0, talkback)
  cb((event) => sink(1, event))
}
```

[Here's the current implementation](https://github.com/saitonakamura/callbag-react-event)
I found this solution acceptable, but it's still kinda ugly in my opinion, especially for the stateless component (this `let handleClick` floating around). Maybe I'm missing something and there's an easier way to do it.

I though about adding a breaking change to the spec which will make callbags pass a value through returns across the pipe of callbags, like 

```
const event = (start, sink) => {
  if (start !== 0) return
  sink(0)
  return (event) => sink(1, event)
}
```
and
```
const observe = operation => source => {
  return source(0, (t, d) => {
    if (t === 1) operation(d);
  });
}
```
In this case we can do something like this, and the best thing is that it can be applied not only to react!
```
class MyComponent extends React.Component {
  handleClick = pipe(
    event,
    observe(event => this.props.onClick(event))
  )

  render() {
    return <button onClick={this.handleClick} />
  }
}
```
But it's still looks kinda hacky to me (and I didn't even think about edge cases) and will require changing of a bunch of existing callbags (which is, given its simplicity, not a very cumbersome task, but still). Sorry for the long post, what do you think about the current solution and spec proposal?

**Comment by franciscotln** [comment]
I believe you could achieve that with a [subject](https://github.com/staltz/callbag-subject)

**Comment by saitonakamura** [comment]
Thanks, @franciscotln , I'll take a look

**Comment by franciscotln** [comment]
I'm not sure if this is what you wanted but have a look @saitonakamura 
https://codesandbox.io/s/1zp0y6jor3

**Comment by saitonakamura** [comment]
That's not as ideal as `fromEvent`, but I can live with that, thank you, @franciscotln !
