### ISSUE TITLE
Is it possible to identify if a function is a Callbag?

### ISSUE THREAD

**Issue by ryansolid** [callbag/callbag#26]
This is an interop question, but symbol-observable has done a ton for observable libraries to be able to talk to each other. I'm just picturing a 'from' type scenario where the input type could be any number of things and you'd want to handle a callbag properly.

**Comment by staltz** [comment]
As long as libraries follow the spec and nothing else, then this is not possible. However, we could certainly attach something like `symbol-callbag` to each function which follows the callbag spec, but then only those functions that have `symbol-callbag` would be identifiable.

I would say it's not a problem that concerns this spec, but if you want that type of guarantee, it's certainly doable within a subset boundary of all callbags.
