### ISSUE TITLE
just curious - why a 'type' parameter instead of separate functions

### ISSUE THREAD

**Issue by far-blue** [callbag/callbag#27]
Hi!

I really enjoyed @staltz's talk at AmsterdamJS yesterday but didn't have a chance to ask (just because I'm curious) why you chose a type parameter on a multi-behavioural function rather than separate functions start(), data() and end().

**Comment by staltz** [comment]
Hi! It's a lighter implementation. Object and 3 methods is more allocations than 1 function.

**Comment by far-blue** [comment]
ah, ok. I didn't realise the difference would be so great :)
