### ISSUE TITLE
Porting to Python

### ISSUE THREAD

**Issue by nsantini** [callbag/callbag#29]
Hi, just to learn I started a repo to port some basic callbags to Python

https://github.com/nsantini/py-callbag-basics

Is this something of interest here? or just JS for this repo?

**Comment by staltz** [comment]
Hi! That's pretty cool! I think it would make sense to fork this standard and make a Python-oriented standard, maybe with its own language-specific requirements. :)

**Comment by staltz** [comment]
Do you want to add this to our Wiki page? :)

**Comment by staltz** [comment]
I added it :)
