### ISSUE TITLE
Backpressure

### ISSUE THREAD

**Issue by ronag** [callbag/callbag#30]
In order to fully support backpressure don't we need to make sure that operators that don't know the e.g. `pause` & `resume` types propagate them upwards?

i.e. could we add to the protocol something like

> if a callbag receives a `type` it doesn't understand it should propagate it.

and maybe possibly a `pause === 3` and `resume === 4`, type?

**Comment by staltz** [comment]
Hi! `pause` and `resume` messages can be passed as type=1, from sink to source. See https://github.com/staltz/callbag-pausable-interval as an example.
