### ISSUE TITLE
A more verbose way to declare callbags : useful ?

### ISSUE THREAD

**Issue by acailly** [callbag/callbag#31]
Hi,

I just created *[callbag-from-verbose](https://github.com/acailly/callbag-from-verbose/blob/master/README.md)*, a way of creating callbags that I found more verbose but also more explicit.

Instead of calling `producer(0, consumer)`, you can call `introduceAtoB(consumer, producer)`
Instead of calling `producer(1, consumer)`, you can call `send(consumer, message)`
Instead of calling `producer(2)`, you can call `stop(consumer)`

And when declaring your callbag, instead of typing: 

```
function producer(type, payload){
  if(type === 0) {...}
  if(type === 1) {...}
  if(type === 2) {...}
}
```

you can type:

```
const producer = fromVerboseCallbag({
  meet: other => { ... },
  receive: message => { ... },
  stop: () => { ... }
})
```

I find it usefull if only to better understand callbags when you're a beginner like me.

And you, do you find this useful too?

PS : I haven't found a better place to chat about this subject. If there is one, please tell me 😉

**Comment by staltz** [comment]
Hi! Well, looks good. Maybe try it out in a real project a couple of times and see if it makes sense. :)

**Comment by DrJume** [comment]
What do you think about this?

```js
const Producer = {
  connect(Consumer) {
    this.i = 0
    this.id = setInterval(() => {
      Consumer.data(this.i++)
    }, 1000)

    Consumer.open(this)
  },
  data(payload) {
    this.i = payload
  },
  end() {
    clearInterval(this.id)
  }
}

const Consumer = {
  open(Producer) {
    setTimeout(() => Producer.data(17), 3500)
    setTimeout(() => Producer.end(), 7500)
  },
  data(payload) {
    console.log(payload)
  }
}

Producer.connect(Consumer)
```

**Comment by acailly** [comment]
@DrJume I like the wording. 
I see you're calling `Consumer.data(...)` directly, how would this work if the Consumer is a raw (not verbose) callbag?

**Comment by DrJume** [comment]
Challenge accepted 😉

**Comment by DrJume** [comment]
Do you have any cool ideas for the name of the spec/library ?

**Comment by bloodyKnuckles** [comment]
As far as names go, when I first heard André share the discovery that, simply, "a Pull is just two Pushes" the first thing came to mind is Doctor Doolittle's "Pushmi-Pullyu" https://youtu.be/pmp-ITOI0-I?t=38s . :)

I wondered about the name Callbags, but then recently in one of André's talks he mentioned that if you take two callback hells, put them each in a bag, then connect the bags together you get heaven—then it clicked. :)  Maybe I heard that explanation here: https://youtu.be/HssczgaY9BM

**Comment by staltz** [comment]
@DrJume Anything you feel like, but here are a few suggestion: objectbag, objbag. Note that forking specs to convert from object prototype methods to functions (or vice-versa) is okay and has happened in other communities, e.g. https://github.com/fantasyland/fantasy-land and then https://github.com/rpominov/static-land
