### ISSUE TITLE
name of the pattern

### ISSUE THREAD

**Issue by andremarcondesteixeira** [callbag/callbag#32]
the name you gave to this pattern is not intuitive. Network or Conversation Pattern would be bettter :)

**Comment by andremarcondesteixeira** [comment]
ok. It was ignorance of my part not knowing that callbag is already a kind known and accepted name. But you could at least gave an answer, couldn't you? How rude. Well, whatever...

**Comment by andremarcondesteixeira** [comment]
Anyway, congratulations for your work. It is definitely awesome.

**Comment by staltz** [comment]
@andremarcondesteixeira Sorry, I have usually dozens of issues to go through every day, so I was hoping that you would figure it out on your own that it's unpractical to rename this pattern at this point, and indeed you did. :) I understand the desire for better names, but naming is hard. I usually go for "easily web-searchable names", so it can bring the community together more easily, and also help when publishing packages on npm. And so far `callbag` was something not used in the wild, so it seemed fair to "claim" it. Would have been hard to search the web or npm for "conversation pattern". Hope you understand. :bowing_man:

**Comment by andremarcondesteixeira** [comment]
Sure thing. I got it now. Thanks for the response and keep up with your
amazing work :D

Em seg, 11 de jun de 2018 16:37, André Staltz <notifications@github.com>
escreveu:
