### ISSUE TITLE
support ES2015 import syntax

### ISSUE THREAD

**Issue by chaosmonster** [callbag/callbag#33]
The examples and (all) callbags use module and require. While this works perfectly in Node.js it won't work in the browser without a bundling step. 
So why not use ES2015 import and export syntax instead, as it is going to be the next standard also for Node.js

**Comment by staltz** [comment]
@chaosmonster Thanks, as mentioned in https://github.com/staltz/callbag-share/pull/7, this issue is specific to each callbag library and does not concern the spec in any way. Callbags as a spec does not have any commitment to using CommonJS.
