### ISSUE TITLE
Use named constants and non-zero power of two values for type parameter

### ISSUE THREAD

**Issue by lhorie** [callbag/callbag#34]
`type = 0` is the reason behind the infamous `typeof null === 'object'` bug and countless other loose equality bugs in the wild. It would be better to use non-zero power of two values instead, which would also allow for things like `type === T_START | T_DATA` should the spec ever allow it in the future

**Comment by staltz** [comment]
Interesting idea, @lhorie, I think you could explore it in a fork of this spec.
