### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by lhorie** [callbag/callbag#35]
Is this spec stable? If so, it should have a release pinned to a version number.

As a side note, it would also be helpful to have historic documentation published for previous versions and a statement about breaking change philosophy (i.e. is it committed to be always backwards-compatible like Ecmascript or does it follow semver).

**Comment by staltz** [comment]
Hi @lhorie! I don't plan to release any breaking changes to this spec. My hope is that this will basically stay 1.0.0 forever. So I'm not yet trying to figure out versioning while it's not yet a problem.
