### ISSUE TITLE
Calling a sourceTalkback with 1 and data

### ISSUE THREAD

**Issue by sunny-g** [callbag/callbag#37]
Are there uses for pulling from sources by sending the source data?

For example, you could build an HTTP client that, when it receives `1, data` can make an HTTP request with that data, and send the responses down the chain of callbags.

Are there problems with using this pattern with callbags? Bad practice? Does it even make sense given the purpose of callbags?

Just trying to get my head around callbags and the thought came up as a potential way of avoiding the costs with long chains of callbags, as well as potentially open the door to preval-ing your callbag-related code so you can compile away the dependencies (premature optimization, I know, but I just wanted to see what has been done in this use case of callbags).

**Comment by staltz** [comment]
> Are there problems with using this pattern with callbags? Bad practice? Does it even make sense given the purpose of callbags?

No problems! Good practice. Makes sense for the purpose of callbags.

What you're describing is requests as pulls. Callbags can be pullables, so this should work just fine.
