### ISSUE TITLE
A more concise way

### ISSUE THREAD

**Issue by langhuihui** [callbag/callbag#43]
Observable: (n,c)=>disposable

> n:d=>void
> c:()=>void
> disposable:()=>void

Operator: source:Observable=>Observable

for example

```js
exports.interval = period => n => {
    let i = 0;
    const id = setInterval(() => n(i++), period)
    return () => clearInterval(id)
}
exports.tap = f => source => (n, c) => source(d => (f(d), n(d)), c);
exports.map = f => source => (n, c) => source(d => n(f(d)), c);
exports.take = count => source => (n, c, _count = count) => {
    const defer = source(d => (n(d), --_count === 0 && (defer(), c())), c)
    return defer
}

exports.subscribe = (n, e = noop, c = noop) => source => source(n, once(err => err ? e(err) : c()))
```

it all works
[sources](https://github.com/langhuihui/rx4rx/blob/master/stdlib/index.js)

**Comment by staltz** [comment]
Hi! That's interesting. What about upstream messages, to support pullables?

**Comment by langhuihui** [comment]
I know what R U talking about. It's easy to do that. Modifing `disposable` function is the only way.  Observable can receive data from the `disposable` function‘s  incoming parameters.

**Comment by mperktold** [comment]
Also, because you only get the `disposable` when the `Observable` returns, you cannot dispose a synchronous source like [callbag-of](https://github.com/Andarist/callbag-of) before it completes.

But if you require that all sources be asynchronous, this is a nice simplification.

**Comment by langhuihui** [comment]
@mperktold I‘ve already considered that situation. You can look at the source code.

**Comment by langhuihui** [comment]
```js
exports.fromArray = array => (n, c, pos = 0, l = array.length) =>
    (setTimeout(() => {
        while (pos < l) n(array[pos++])
        c()
    }), () => (pos = l, c = noop))

exports.of = (...items) => exports.fromArray(items)
```
by using setTimeout , I can dispose 'of'

**Comment by staltz** [comment]
It seems this issue is about an alternative spec, so I recommend creating your own project for that. Callbag is going to stay backwards compatible.
