### ISSUE TITLE
Are asynchronous handshakes permitted?

### ISSUE THREAD

**Issue by mattflix** [callbag/callbag#44]
The callbag spec doesn't seem to indicate whether asynchronous handshakes are permitted.  It uses only the language "greeting back", without indicating how this may occur (in terms of timing).

I can imagine source implementations that must perform some work before they are able to logically "commit" to greeting back their sinks.  Is any delay in handshaking allowed, or is expected that all greeting be strictly synchronous?

Related, what if source initialization fails?  Should the source greet the sink back anyway, and then perhaps push nothing but an error (2 with truthy payload) to its sink, ignoring all other interim requests (if any) from the sink?

**Comment by staltz** [comment]
All inter-callbag communication is synchronous or asynchronous, there should not be any bias towards sync or async, the spec should work either way. So this means handshakes can be asynchronous and slow. What matters most is the order of communication. Type `0` MUST come before type `1`. And type `2` must be the last. If source initialization fails, the source should greet back and immediately end with type `2`.
