### ISSUE TITLE
Express variance in types

### ISSUE THREAD

**Issue by devanshj** [callbag/callbag#52]
Putting it in the best type theoretical way I can muster, afaict, `Callbag<I, O>` is covariant on `I` and contravariant on `O`. (eg: `Source<"a" | "b">` should not be assignable to `Source<"a">`)

This isn't expressed in types (ie with current types [you can assign `Source<"a">` to `Source<"a" | "b">`][1] which shouldn't be allowed as it can cause runtime errors). This can be simply [fixed by using an interface][2] instead of a type alias.

Moreover, it would nice to use interfaces for `Source` and `Sink` as well as it would preserve names in error messages (right now error messages have `Callbag<never, T>` instead of `Source<T>` as type aliases [don't "create new names"][3])

If the changes are agreed upon I would love to send a PR! :)

EDIT: Also this would be a breaking change but only for those who already have error-prone code so imo no need for a major bump

[1]: https://www.typescriptlang.org/play?#code/IYIwyg9grgTgxgUwAQF4nErRAoA9LpAAQBcBnAWgQA8AHBOYymGCGbDaeZNUTL7PARIVqdBkxZteASwB2Aa1Towc+exUKlMhQIAm9ADbAYyAwmLLOiAFxIAwsAMGQwAOYAeWQgBuCGABokACJgIIA+bH04IxMkMwteKwRbBycXDy9fAODQpAAfYJBwyMNjU3NlVRTHZzd3EKDAzL8IqJjyhPAq+xr0+tyCoKKmnxaBYgBPOh60uoBJQIB5MKUAb2wkJAAKYlsABkDdatmPRcC5sIBKW28IaV0Abg3t3aQARkPbOeukW-unzY7WwAJkOAH5bMBZBMfn9HtgAL4PIA

[2]: https://www.typescriptlang.org/play?#code/IYIwyg9grgTgxgUwAQF4nErRAoA9LpAAQBcBnAWgQA8AHBOYymGCGbDaeZNUTL7PARIVqdBkxZteASwB2Aa1Towc+exUKlMhQIAm9ADbAYyAwmLLOiAFxIAwsAMGQwAOYAeWQgBuCGABokACJgIIA+bH04IxMkMwteKwRbBycXDy9fAODQpAAfYJBwyMNjU3NlVRTHZzd3EKDAzL8IqJjyhPAq+xr0+tyCoKKmnxaBOWI-ADNgRB60uoBJQIB5MKQAb2wkJAAKYlsABkDdaoWPFcDFsIBKW28IaV0Abm29g6QARhPbRbukB5PV47fa2ABMJwA-LZgLIAJ7-QEvbAAX2eQA

[3]: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN7LgLmQIjn2QF8AoUSWRFAIWQgA9IQATAZzU3LAE8AHFAGFkAXjQBuMmQD0M5AAUoAe0FQ+yAOQAjTcmCcAtgfagA5vpDI+graj3aArmGRQIAR0fA3rS9YEomljaePja+BKkmgB0svLICYlJySmpSQB6mcgAFEyCCJC+ImbKLqgAlGQIyiDsLiDKAEoQIHDGIGZ4waHhpGLc2JxCUnGKKmoaOnoGyMbsph1+NoG0Ds6uHl4+SwFa3QThkSQxo2ln58mZ6Tl5EAUQvvQlLrSV1bUubq3tnZjIIQdiCR+hhgXBOLQJEA

**Comment by staltz** [comment]
Hmm, I think this would be reasonable as a PR.

Thoughts @Andarist @loreanvictor ?

**Comment by Andarist** [comment]
Makes sense to me - the only part I don't get (although I can't confirm, obviously) is why using `interface` over `type` changes the variance here? It's the very first time I've learned about this 😱

**Comment by devanshj** [comment]
I don't really have an answer, even I learnt this today xD altho usually one doesn't have to bother about variance as typescript derives it from the implementation (like [here][1], works even with type alias). I'm suspicious that in case of callbags typescript can't do that because of the either simultaneous covariance and contravariance or the recursiveness of the definition because weirdly enough if I write separate types for sink and source [it works even with type aliases][2]

[1]: https://www.typescriptlang.org/play?#code/C4TwDgpgBA8gRgZwgJwG4EM4BsIB4AqAfFALxQDeAUFFAgK6IDGyAlnBAFxQAUAZl9wAeXfAEpSxVAHsWAE3Eli3clDoA7ek1bsBCyTNlQAvqMpHKlWREZZ0yaDmBR0AEi7wkaTDlwAidL6EANyW1rb2UI7OcG6wiCgY2Hj+vlAAPlC+cIEWAPS5UAACwAgAtBCCkIzA5cjIUsiUrqTRLkA

[2]: https://www.typescriptlang.org/play?#code/IYIwyg9grgTgxgUwAQF4nErRAoA9LpAAQBcBnAWgQA8AHBOYymGCGbDaeZNUTL7PARIVqdBkxZteASwB2Aa1Towc+exUKlMhQIAm9ADbAYyAwmLLOiAFxI+iADwAiYE4B82fXCMmkZi7xWCLb2CM6uSAA+SE4g7p6GxqbmyqohquHxXj7JAeBpdhkuTlExcR7YxACedHZBDgAqbkoA3thISAAUxLYADAA0SLrpCo1uAJS2AG4Q0roA3O1dPUgAjIPDSLIIUwgwk0gzc4sd3bYATBsA-LbAslUHRwvYAL6LlTXIGvJjrUtnSAGQxC9Saj1mz1OK3WwKQDXBx3+K0uQxu6HuCOeLyAA

**Comment by Andarist** [comment]
<img src="https://media.giphy.com/media/AYMzMAgZIci8IgezfQ/giphy.gif" />

**Comment by loreanvictor** [comment]
I fail to understand the issue with assignability. `Sink<A | B>` should be assignable to `Sink<A>`, and not the inverse, i.e.:
```ts
const a1: Sink<A> = makeSink<A | B>()        // --> this should be ok
const a2: Sink<A | B> = makeSink<A>()       // --> this should be an error
```
and [this is the case with current typings](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDKAVAggJQ3AXjgAYBuAKFElgWVQBEttC4BGCq6eJFOAUQBy9FgCYKlcF1q8AwgEMANgoBGcgOYAeAJIAaOAHkAfCwDe5OHAAUMAFzpsePQBM78pas369WwwEo7AG4QAJZOFBbWdozYznZa-nBBoeFWtvxCzgD8dnIAdogJSWHkAL7inDQ8qGgQAK5QAMbAGhjGRG4q6hq5wAHAUHqtHJKVdOjBuQDWLW1wHR4tej19UIbiTsANCnJQqABmtbkNMMEQuXAAtnKTwGgT062WCXdTMxQbWzv7h8en51c3eZdXQGQxPVyKTqaEFGcQNM4AZ3gclYdhe0wA5FgMbMAbd7hosRi4AAfOAYgBCOKeFHhuSRcDkIjRBKJpPJVNx13xryJYN8cMRyIAzBD3F0iUtev0uYDIQs2WTKRipSt+bShYyACxiqGE7Hs5WqmUsPFAzSSuDLGU08hAA).

> To explain, you can treat `Sink<A | B>` as `Sink<A>` since you can just feed it `A` and it's ok since `A` is `A | B`. You cannot treat `Sink<A>` as `Sink<A | B>` since you cannot feed it `B`.

**Comment by loreanvictor** [comment]
That said, it seems like we have the issue with `Source`s actually, since `Source<A | B>` should not be assignable to `Source<A>`, [but it is](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDKAVAggJQ3AXjgAYBuAKFElgWVQBEttC4BGCq6eJFOAUQBy9FgCYKlcF1q8AwgEMANgoBGcgOYAeAJIAaOAHkAfCwDe5OHAAUMAFzpsePQBM78pas369WwwEo7AG4QAJZOFBbWdozYznZa-nBBoeFWtvxCzgD8dnIAdogJSWHkAL7inDQ8qGgQAK5QAMbAGhjGRG4q6hq5wAHAUHqtHJKVdOjBuQDWLW1wHR4tej19UIbiTsANCnJQqABmtbkNMMEQuXAAtnKTwDX1TTOWCXeNzUPkG1s7+4fHp+dXG7zLq6AyGJ6uRSdTSgoziBpnADO8DkrDsLweAHIsJjZoDbnVXhpsZi4AAfOCYgBCuKeFARuWRcDkInRhKxOPJlJpeOuBPuzRJ4N88KRKIAzJD3F1lv09EKWPjgZpZQNKZyKdTaSLyAymXIACxS6HdXpy9WkzU8xV85WmlbynHCihAA).

> To explain, you cannot treat `Source<A | B>` as `Source<A>`, since `Source<A>` only emits `A`s but `Source<A | B>` can emit `B`s.

**Comment by devanshj** [comment]
Yep the problem in with `Source`, I actually meant `Source` in the OP just a typo xD

**Comment by loreanvictor** [comment]
> Yep the problem is with `Source`, I actually meant `Source` in the OP just a typo xD

Yeah the proposed solution (changing everything to interfaces) [does fix the issue with `Source` while keeping it consistent with `Sink`s](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDKAVAggJQ3AXjgAYBuAKFElgWVQBEttC4BGCq6eJFOAUQBy9FgCYKlcFzgBLAHYxgUAGYBDAMaoAwioA2OgEYqA5gB4AkgBo4AeQB8cAN7k4cABQwAXOmx4rAEy9tPUNTayszWwBKLwA3CGk-Chd3L0Zsfy8zaLg4hKS3T34hfwB+LxVZRGzcxPIAX3FOGjkFZXVUNAgAVygNEwx7UAVZPwBnOCCDYxNZYBjFKwHHOolqeBbFVQ10OQBrfsGQYbGJ3SnTDCtZ+ah7BxXyP2A1HRUoVCUu2TUYaQhZOAAWxUu2AaD2B1c2XBsn2AwoTxebw+Xx+fwBwNBnR6fQGUK82N6wAOCOer3ecE+31+-yBIOAkxC5isdnxp2C00sNls4jU-1G8BUrAJEIA5FhRfYiJiwWKJXAAD5wUUAIUlUIofNkArgKhEIthJnFosVyrVUrpWLl6sivP5goAzIEzkzjVc5ooLTLGdNjabVaL3TdbBryFqdSoACzOjmmP1KgNBz0sb0u30SpO3UNh+1wUbC9DdIlGiVe+mEvrxs02zW50b6ws44lVgNlrFFyul7Ph+CjJ3s84zD1QKzGtsMtOma4LZXyhPm0M9vPRgdM6cj2cm+eSlP0n1T4ejru2oA), as weird as that is :)))

And yes I also would appreciate better DX that we would get by named messages and errors (`Callbag<T, never>` and `Callbag<never, T>` are pretty confusing).

**Comment by jvanbruegge** [comment]
I don't know how typescript handles variance, but naturally variant type variable rise from usage in positive position while contravariance comes from negative usage.
Ie, for functions this means `type Foo<T> = (arg: T) => void;` uses t in positive position and thus T is variant and `type Bar<T> = () => T` has `T` in negative position and thus should be contravariant.

**Comment by Andarist** [comment]
I'm not super strong when it comes to those terms but AFAIK TS treats this: `type Foo<T> = (arg: T) => void;` as contravariant and if I only understand that term correctly it makes sense as otherwise this wouldn't be sound:
https://www.typescriptlang.org/play?#code/MYGwhgzhAECCB2BLAtmE0DeAoa0DuaA1gBQCUmAvllaJDACID2A5tAKYAeALm-ACYwEKNJhzQARmABOJchipUsAMwCu8YF0SN40MMGBsADlyGoQxMEjMAuOFbRyqq9Zu279Rrk2bE+LW95yYn7MAHSSMmTUWFjA2hBc0DwJtlwAnoZsjEruBsamIgC8uZ7eWMlcxPBseHbC5qSkQA

**Comment by devanshj** [comment]
Yep, probably @jvanbruegge mistakenly replaced covariant and contravariant afaiu. Didn't exactly got your proof but a much simpler one [here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwg9gO2AJwIYDdXIJaqQHgBUA+KAXigAoAPALikIEpzT05sATAbgCgeBjRAGdgUOlABEqCVAA+kgEYyKAbwC+UVEMnTeghCLEBBMGAA22CB3rwkaTDjzB8UmfIlLSqjVtiIUGFi4BK7EvDygkH4Owc4k5FTMZKSE4fqGIPSucorKUOqa2q56wqIgJuaW1tFBTi7SOR4SXvk+2vAxdaHhAPQ9UNgAZlAAXlAAFnBmHNp4HKMVFlZQHHAQQggA5KLYogC2qADW61DA49DIEGaowNiIUPoBnUhQcGcQyADu2ELQgs-AIA)

**Comment by jvanbruegge** [comment]
Ah, yes, sorry, the two terms should be swapped. That's a typo
