### ISSUE TITLE
Missing index.js referenced from "main" in package.json breaks Vite

### ISSUE THREAD

**Issue by jesseskinner** [callbag/callbag#65]
I'm unable to use callbag with Vite, due to the "main" field in `package.json` being set to `index.js`, which does not exist.

I get the following error:

```
  The plugin "vite:dep-scan" was triggered by this import

    index.ts:1:23:
      1 │ import { Source } from 'callbag';
        ╵                        ~~~~~~~~~

Build failed with 1 error:
node_modules/.pnpm/vite@2.9.9/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:40662:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "callbag". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "callbag". The package may have incorrect main/module/exports specified in its package.json.
```

I set up a little repo to demo the problem, if needed: https://github.com/jesseskinner/callbag-vite-test

To solve this, I believe you could ether replace "index.js" with "types.d.ts" in the "main" field, just remove the "main" field, or create a dummy placeholder `index.js` file.

Thanks!

**Comment by staltz** [comment]
Fixed in version 1.5.1, thanks for the tip!
